# Generated by Django 5.0.6 on 2024-05-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
